/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-04-18 09:14:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>客户关系管理系统登录</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.min.js\"></script>\r\n");
      out.write("<STYLE type=text/css>\r\n");
      out.write("BODY {\r\n");
      out.write("\tTEXT-ALIGN: center;\r\n");
      out.write("\tPADDING-BOTTOM: 0px;\r\n");
      out.write("\tBACKGROUND-COLOR: #ddeef2;\r\n");
      out.write("\tMARGIN: 0px;\r\n");
      out.write("\tPADDING-LEFT: 0px;\r\n");
      out.write("\tPADDING-RIGHT: 0px;\r\n");
      out.write("\tPADDING-TOP: 0px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:link {\r\n");
      out.write("\tCOLOR: #000000;\r\n");
      out.write("\tTEXT-DECORATION: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:visited {\r\n");
      out.write("\tCOLOR: #000000;\r\n");
      out.write("\tTEXT-DECORATION: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:hover {\r\n");
      out.write("\tCOLOR: #ff0000;\r\n");
      out.write("\tTEXT-DECORATION: underline\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("A:active {\r\n");
      out.write("\tTEXT-DECORATION: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input {\r\n");
      out.write("\tBORDER-BOTTOM: #ccc 1px solid;\r\n");
      out.write("\tBORDER-LEFT: #ccc 1px solid;\r\n");
      out.write("\tLINE-HEIGHT: 20px;\r\n");
      out.write("\tWIDTH: 182px;\r\n");
      out.write("\tHEIGHT: 20px;\r\n");
      out.write("\tBORDER-TOP: #ccc 1px solid;\r\n");
      out.write("\tBORDER-RIGHT: #ccc 1px solid\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input1 {\r\n");
      out.write("\tBORDER-BOTTOM: #ccc 1px solid;\r\n");
      out.write("\tBORDER-LEFT: #ccc 1px solid;\r\n");
      out.write("\tLINE-HEIGHT: 20px;\r\n");
      out.write("\tWIDTH: 120px;\r\n");
      out.write("\tHEIGHT: 20px;\r\n");
      out.write("\tBORDER-TOP: #ccc 1px solid;\r\n");
      out.write("\tBORDER-RIGHT: #ccc 1px solid;\r\n");
      out.write("}\r\n");
      out.write("</STYLE>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\tvar userName=$(\"#userName\").val();\r\n");
      out.write("\t\tvar password=$(\"#password\").val();\r\n");
      out.write("\t\tvar roleName=$(\"#roleName\").val();\r\n");
      out.write("\t\tif(userName==null||userName==\"\"){\r\n");
      out.write("\t\t\talert(\"用户名不能为空！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(password==null||password==\"\"){\r\n");
      out.write("\t\t\talert(\"密码不能为空！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(roleName==null||roleName==\"\"){\r\n");
      out.write("\t\t\talert(\"请选择用户类型！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#adminlogin\").submit();\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<FORM id=adminlogin  method=post\r\n");
      out.write("\tname=adminlogin action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/login.do\"  >\r\n");
      out.write("<DIV></DIV>\r\n");
      out.write("<TABLE style=\"MARGIN: auto; WIDTH: 100%; HEIGHT: 100%\" border=0\r\n");
      out.write("\tcellSpacing=0 cellPadding=0>\r\n");
      out.write("\t<TBODY>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD height=150>&nbsp;</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR style=\"HEIGHT: 254px\">\r\n");
      out.write("\t\t\t<TD>\r\n");
      out.write("\t\t\t<DIV style=\"MARGIN: 0px auto; WIDTH: 936px\"><IMG\r\n");
      out.write("\t\t\t\tstyle=\"DISPLAY: block\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/body_03.jpg\"></DIV>\r\n");
      out.write("\t\t\t<DIV style=\"BACKGROUND-COLOR: #278296\">\r\n");
      out.write("\t\t\t<DIV style=\"MARGIN: 0px auto; WIDTH: 936px\">\r\n");
      out.write("\t\t\t<DIV\r\n");
      out.write("\t\t\t\tstyle=\"BACKGROUND: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/body_05.jpg) no-repeat; HEIGHT: 155px\">\r\n");
      out.write("\t\t\t<DIV\r\n");
      out.write("\t\t\t\tstyle=\"TEXT-ALIGN: left; WIDTH: 265px; FLOAT: right; HEIGHT: 125px; _height: 95px\">\r\n");
      out.write("\t\t\t<TABLE border=0 cellSpacing=0 cellPadding=0 width=\"100%\">\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD style=\"HEIGHT: 45px\"><INPUT type=\"text\" class=input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"userName\" id=\"userName\"></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD><INPUT type=\"password\" class=input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.password }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"password\" id=\"password\"/></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"roleName\" name=\"roleName\" class=\"input\" style=\"margin-top: 15px;height: 24px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">请选择用户类型...</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"系统管理员\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'系统管理员'==user.roleName?'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">系统管理员</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"销售主管\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'销售主管'==user.roleName?'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">销售主管</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"客户经理\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'客户经理'==user.roleName?'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">客户经理</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"高管\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'高管'==user.roleName?'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">高管</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("\t\t\t<DIV style=\"HEIGHT: 1px; CLEAR: both\"></DIV>\r\n");
      out.write("\t\t\t<DIV style=\"WIDTH: 380px; FLOAT: right; CLEAR: both\">\r\n");
      out.write("\t\t\t<TABLE border=0 cellSpacing=0 cellPadding=0 width=300>\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD width=100 align=right><INPUT\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"BORDER-RIGHT-WIDTH: 0px; BORDER-TOP-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px\"\r\n");
      out.write("\t\t\t\t\t\t\tid=btnLogin src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/btn1.jpg\" type=image name=btnLogin onclick=\"javascript:login();return false;\"></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=100 align=middle><INPUT\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"BORDER-RIGHT-WIDTH: 0px; BORDER-TOP-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px\"\r\n");
      out.write("\t\t\t\t\t\t\tid=btnReset src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/btn2.jpg\" type=image name=btnReset onclick=\"javascript:adminlogin.reset();return false;\"></TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("\t\t\t<DIV style=\"MARGIN: 0px auto; WIDTH: 936px\"><IMG\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/body_06.jpg\"></DIV>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR style=\"HEIGHT: 30%\">\r\n");
      out.write("\t\t\t<TD>&nbsp;</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TBODY>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</FORM>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script type=text/javascript>\r\n");
      out.write("\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'!=''){\r\n");
      out.write("\t\talert('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
